### ISSUE TITLE
all oAuth strategies dont work

### ISSUE THREAD

**Issue by basiclaser** [rkusa/koa-passport-example#12]
If your intention was for the fb, twitter, google strategies to be working in the demo, they are currently not.

**Comment by rkusa** [comment]
Habe you updated [`auth.js`](https://github.com/rkusa/koa-passport-example/blob/master/auth.js) with actual client ids/secrets?

**Comment by basiclaser** [comment]
yes sorry i rushed in too fast expecting it to work immediately, it immediately worked when i added my keys. Thanks.
