### ISSUE TITLE
[question] async function on Strategy example

### ISSUE THREAD

**Issue by sibelius** [rkusa/koa-passport-example#14]
Is there any example of how to use an async function for a Strategy, like:

```javascript
passport.use(new LocalStrategy(async (username, password, done) => {
   const user = await User.findOne({username: username})

   if (user) {
      done(null, user)
   } else {
       done(null, false)
   }
}))
```

**Comment by rkusa** [comment]
In my own project, I currently use an ugly workaround:

```js
new LocalStrategy(opts, function(email, password, done) {
  co(function*() {
    const user = yield User.byEmail(email)

    ...

    return user
  }).then(res => done(null, res), done)
})
```

I did not invest time into finding a better solution for this. Especially, because these strategies are out of scope of `koa-passport`. That is, there is either a wrapper necessary (but maybe not as ugly as in my example above), or there has to be something like `koa-passport-local`.

**Comment by luodaxu** [comment]
Hi, I use the code below, it works, but is it fine ?
 (async function() {
        let user = await User.getExistUser(username, password);
        if(user) {
            done(null, user);
        } else {
            done(null, false);
        }
    })();

**Comment by rkusa** [comment]
Looks good to me. However, I have not played with `async/await` myself yet. That is, I may not be the best person to trust on that ;-)

But now I am curious... does the following work?

```js
    new LocalStrategy(opts, async function(email, password, done) {
        let user = await User.getExistUser(username, password);
        if(user) {
            done(null, user);
        } else {
            done(null, false);
        }
    });
```

**Comment by sibeliusseraphini** [comment]
@rkusa it works, thanks.

You should start using async/await it is great

**Comment by benbonnet** [comment]
Hello,
the following returns an error :
 
```
const strategy = new GoogleStrategy(
  config,
  async (accessToken, refreshToken, params, profile, done) => {
    const user = await signUser(accessToken, refreshToken, params, profile);
    return user;
  }
);
```

can't passport just receive a returned object ?

**Comment by rkusa** [comment]
No, passport can unfortunately not. Passport strategies do not work well with async functions / with functions returning a Promise.
