### ISSUE TITLE
Include / link to example using a database

### ISSUE THREAD

**Issue by mapmeld** [rkusa/koa-passport-example#16]
Hi Markus,

I'm using Koa 2.0 and koa-passport in my app now and it's awesome. The most difficult part was translating the example code and scripts into workable examples, where there are users stored in the database, potentially multiple users, csrf protection, sessions, etc. I understand the point of keeping this example code simple, but this simplified code proved unhelpful when I wanted to implement koa-passport in a real app.

Can this repo include or link to real-world examples of koa-passport? My own mongodb code is available here https://github.com/mapmeld/koa-passport-example

I'm writing a more detailed example app at https://github.com/mapmeld/1batch/wiki though I just moved it from Express to Koa v2, so that's not complete yet 

-- Nick

**Comment by rkusa** [comment]
Hi, I am totally fine with adding a link to more examples. Just send me a PR that adds the link to the Readme. Thanks!

**Comment by rkusa** [comment]
#17 merged
