### ISSUE TITLE
ctx.req.user being called by a dependency

### ISSUE THREAD

**Issue by mapmeld** [rkusa/koa-passport-example#20]
With the latest update to koa-passport, I get a ```koa-passport deprecated setting ctx.req.user is deprecated in favour of ctx.state.user``` warning when I log in

This codebase doesn't use ```ctx.req``` or ```ctx.state```, so my best guess is that it's coming from ```koa-route``` or another dependency.

**Comment by rkusa** [comment]
Thanks for reporting, I'll track the progress on this issue in rkusa/koa-passport#66

**Comment by mapmeld** [comment]
looks like this is fixed! I updated my example
Thanks!
