### ISSUE TITLE
Update for Async/Await

### ISSUE THREAD

**Issue by appurist** [rkusa/koa-passport-example#22]
I've seen the comments in [koa-passport #63](https://github.com/rkusa/koa-passport/issues/63),  but I was wondering if there was any movement towards getting this example updated with async/await now that it's been available in Node 7 for a few releases.

**Comment by appurist** [comment]
Okay somehow I missed the work you had already done in your most recent commits. I think the use of promises rather than async/await in those places threw me off at bit, but it looks like converting those remaining cases to async/await just makes the code larger and messier anyway, so I think we can close this one as already complete!

Thanks for the great example code.

**Comment by rkusa** [comment]
> (No promises, but...) I might be able to take a stab at it myself, if nobody else is working on it, but I do want to avoid duplication of effort, if you or someone else was or wanted to do that update.

Thanks for the intention to help! 😊
