### ISSUE TITLE
using generator function in callback function

### ISSUE THREAD

**Issue by aisk** [rkusa/koa-passport-example#7]
When create a XXXStrategy, I can only pass a callback style on auth function, but I want use generator style function, how to do that? thanks.

**Comment by ApelSYN** [comment]
Koa-passport designed to use the existing * Strategies for the original Passport. Therefore, to create their strategy is used
https://github.com/jaredhanson/passport-strategy

Inside his strategy you can connect "co" and use generators

**Comment by aisk** [comment]
Thanks ~

**Comment by rkusa** [comment]
Thanks @ApelSYN the explanation! @aisk hope you were able to solve your issue
