### ISSUE TITLE
Doesn't run "TypeError" exception

### ISSUE THREAD

**Issue by romu70** [rkusa/koa-passport-example#9]
Hi,
Trying to run the example and an exception is raised on line 15:

```
app.use(bodyParser())
```

Error trace:

```
TypeError: Support for generators has been removed.
```

I run Koa2-alpha3.

**Comment by rkusa** [comment]
Do you have body-parser version 3 installed?

**Comment by romu70** [comment]
Obviously no, but I would have expected it would be installed with koa-bodyparser, am I wrong?

**Comment by rkusa** [comment]
Unfortunately not, for `koa@2` itself and all compatible middlewares, the NPM `latest` tag (which is installed with `npm install koa-bodyparser`) will still install `koa@1` (and compatible middleware respectively). Instead, the `next` tag is used for `koa@2` compatible stuff. That is, you could use `npm install koa-passport@next`.

**Comment by romu70** [comment]
Yes, my mistake, sorry, I'm a bit newbie.

I've just install koa-passport@next this also installed koa-bodyparser 2.0.1. Same issue. So, I guess I've to install the ```body-parser``` package, but last version is 1.14.2, not 3.

Thanks for your help.

**Comment by rkusa** [comment]
Sorry I had an error in my previous comment. I mean `npm install koa-bodyparser@next` and not `npm install koa-passport@next`. Does this help?

**Comment by romu70** [comment]
Much better @rkusa, I still miss some other modules, but I'm going to read a bit more to see which are necessary. Currently, this issue is gone.

**Comment by rkusa** [comment]
You are welcome. You can also use `koa-convert` to convert koa@1 middleware to koa@2 middleware.
